site_name: cfsem
site_url: https://cfsem.readthedocs.io
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - "About cfsem": index.md
  - "Python Examples": "python/examples.md"
  - "Python API":
      - "python/filament.md"
      - "python/flux_density.md"
      - "python/inductance.md"
      - "python/grad_shafranov.md"
      - "python/math.md"
      - "python/types.md"
  - "Rust API": "https://docs.rs/cfsem"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - cfsem

exclude_docs: |
  rust/static.files/SourceSerif4-LICENSE-*.md
