[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "cfsem"
dynamic = ["version"]
description = "Quasi-steady electromagnetics including filamentized approximations, Biot-Savart, and Grad-Shafranov."
authors = [{name = "Commonwealth Fusion Systems", email = "jlogan@cfs.energy"}]
requires-python = ">=3.10, <3.14"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "numpy >= 2",
    "interpn[pydantic]>=0.8.2,<0.12",
    "findiff ~= 0.13.1",
    "pydantic ~= 2.0",
    "pydantic-numpy ~= 6.0",
    "scipy ~= 1.8",
]
license = "MIT"

[dependency-groups]
dev = [
    # Tests
    "pytest == 9.0.2",
    "pytest-cov == 7.1.0",
    "ruff == 0.6.2",
    "ty == 0.0.42",
    # Docs
    "mkdocs == 1.6.0",
    "mkdocs-material == 9.5.25",
    "mkdocstrings[python] == 1.0.3",
    # Examples
    "matplotlib ~= 3.10",
    "plotly>=6.6.0,<7",
    "dash>=4.0.0,<5",
    "griffe==2.0.2",
]

[tool.maturin]
features = ["python"]
module-name = "cfsem.cfsem"
version = "cargo"
profile = "release"

[tool.ruff]
line-length = 110
exclude = ["vendor"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
]

[tool.coverage.report]
fail_under = 100

[tool.pytest.ini_options]
norecursedirs = ["vendor", "target", ".venv", "dist", "build"]
addopts = "--cov=cfsem --cov-report=html --cov-report=term-missing --cov-fail-under=100"
